Models/Passanger/PassengerProfileViewModel.cs
namespace Airline.Models;

public class PassengerProfileViewModel
{
    public string ProfilePicture { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string FullName => $"{FirstName} {LastName}";
    public string Email { get; set; }
    public string PhoneNumber { get; set; }
    public string Address { get; set; }
    public DateTime DateOfBirth { get; set; }
    public string Nationality { get; set; }
    public string PassportNumber { get; set; }
    public string FrequentFlyerNumber { get; set; }
    
    // Loyalty Program Properties
    public string LoyaltyTier { get; set; }
    public int LoyaltyProgress { get; set; }
    public int PointsToNextTier { get; set; }
    public int TotalMiles { get; set; }
    public int AvailablePoints { get; set; }
}

Models/Passenger.cs
using System;

namespace Airline.Models
{

    public class Passenger
    {

        public string Passport_No { get; set; }


        public string Name_ { get; set; }


        public string Gender { get; set; }

 
        public DateTime Birth_Date { get; set; }
        
        public string Contact_Info { get; set; }

  
        public string Nationality { get; set; }


        public string Email { get; set; }

 
        public string Address { get; set; }
    }
}

Models/RefundRequest.cs
public class RefundRequest
{
    // Ticket_ID, Amount, date_, Status_, description_
    public string Ticket_ID { get; set; }
    
    public int Amount { get; set; }
    
    public DateTime date_ { get; set; }
    
    public string Status_ { get; set; } = "Pending";
    
    public string description_ { get; set; }

}

Models/TicketDetails.cs
namespace Airline.Models;

public class TicketDetails
{
    public Ticket ticket { get; set; }
    public Flight flight { get; set; }
    public Route route { get; set; }
}

Models/TicketRecordViewModel.cs
public class TicketRecordViewModel
{
    public List<Ticket> Tickets { get; set; }
    public List<Flight> Flights { get; set; }
    public List<Route> Routes { get; set; }
}

Controllers/PassengerController.cs
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using Airline.Models;

public class PassengerController : Controller
{
    string connStr = "server=localhost;port=3306;user=root;password=mradwan#1MySql;database=airline;";


    [HttpGet("passenger/profile/{Passport_No}")]
    public IActionResult PassengerProfile(string Passport_No)
    {
        Passenger passenger = null;


        using (var conn = new MySqlConnection(connStr))
        {
            conn.Open();
            string query = "SELECT * FROM passenger WHERE Passport_No = @Passport_No";
            using (var cmd = new MySqlCommand(query, conn))
            {
                cmd.Parameters.AddWithValue("@Passport_No", Passport_No);
                using (var reader = cmd.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        passenger = new Passenger
                        {
                            Passport_No = reader["Passport_No"].ToString(),
                            Name_ = reader["name_"].ToString(),
                            Gender = reader["gender"].ToString(),
                            Address = reader["Address"].ToString(),
                            Birth_Date = reader.GetDateTime("birth_date"),
                            Contact_Info = reader["contact_info"].ToString(),
                            Email = reader["Email"].ToString(),
                            Nationality = reader["Nationality"].ToString(),
                        };
                    }
                }
            }
        }


        return View(passenger);
    }


    [HttpGet("passenger/TicketRecord/{Passport_No}")]
    public IActionResult TicketRecord(string Passport_No)
    {
        var viewModel = new TicketRecordViewModel
        {
            Tickets = new List<Ticket>(),
            Flights = new List<Flight>(),
            Routes = new List<Route>()
        };

        using (var conn = new MySqlConnection(connStr))
        {
            conn.Open();
            string query = """
                           SELECT 
                               t.Ticket_ID, 
                               t.Class, 
                               t.Pay_Status, 
                               f.depart_time, 
                               r.start_airport, 
                               r.end_airport, 
                               r.base_price
                           FROM 
                               Ticket t
                           JOIN 
                               Flight f ON t.Flight_ID = f.fid
                           JOIN 
                               Route r ON f.route_id = r.ro_id
                           WHERE 
                               t.Passport_No = @Passport_No;
                           """;

            using (var cmd = new MySqlCommand(query, conn))
            {
                cmd.Parameters.AddWithValue("@Passport_No", Passport_No);
                using (var reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        viewModel.Tickets.Add(new Ticket
                        {
                            Ticket_ID = reader["Ticket_ID"].ToString(),
                            Class = reader["Class"].ToString(),
                            Pay_Status = reader["Pay_Status"].ToString()
                        });

                        viewModel.Flights.Add(new Flight
                        {
                            depart_time = reader.GetDateTime("depart_time")
                        });

                        viewModel.Routes.Add(new Route
                        {
                            start_airport = reader["start_airport"].ToString(),
                            end_airport = reader["end_airport"].ToString(),
                            base_price = reader.GetDecimal("base_price")
                        });
                    }
                }
            }
        }

        for (int i = 0; i < viewModel.Tickets.Count; i++)
        {
            if (viewModel.Tickets[i].Class == "First")
            {
                viewModel.Routes[i].base_price = viewModel.Routes[i].base_price * 1.5m;
            }
            else if (viewModel.Tickets[i].Class == "Business")
            {
                viewModel.Routes[i].base_price = viewModel.Routes[i].base_price * 2.0m;
            }
        }
        
        return View(viewModel);
    }

    [HttpGet("passenger/TicketDetails/{id}")]
    public IActionResult TicketDetails(string id)
    {
        Airline.Models.TicketDetails ticketDetails = new Airline.Models.TicketDetails();

        using (var conn = new MySqlConnection(connStr))
        {
            conn.Open();
            string query = """
                           SELECT *
                           FROM 
                               Ticket t
                           JOIN 
                               Flight f ON t.Flight_ID = f.fid
                           JOIN 
                               Route r ON f.route_id = r.ro_id
                           WHERE 
                               t.Ticket_ID = @Ticket_ID;
                           """;

            using (var cmd = new MySqlCommand(query, conn))
            {
                cmd.Parameters.AddWithValue("@Ticket_ID", id);
                using (var reader = cmd.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        // Handle Discount
                        string discountStr = reader["discount"].ToString();
                        decimal discountValue = 0;
                        if (!string.IsNullOrWhiteSpace(discountStr) && discountStr.EndsWith("%"))
                        {
                            discountStr = discountStr.TrimEnd('%');
                            discountValue = decimal.Parse(discountStr) / 100;
                        }

                        // Convert duration to TimeSpan
                        TimeSpan flightDuration;
                        if (reader["duration"] is int durationInt)
                        {
                            flightDuration = TimeSpan.FromMinutes(durationInt); // Adjust this based on your data
                        }
                        else if (reader["duration"] is TimeSpan durationTimeSpan)
                        {
                            flightDuration = durationTimeSpan;
                        }
                        else
                        {
                            throw new InvalidCastException("Invalid duration data type");
                        }

                        ticketDetails.ticket = new Ticket
                        {
                            Ticket_ID = reader["Ticket_ID"].ToString(),
                            Passport_No = reader["Passport_No"].ToString(),
                            Class = reader["Class"].ToString(),
                            Pay_Status = reader["Pay_Status"].ToString(),
                            Payment_method = reader["Payment_method"].ToString(),
                            Seat_id = reader["seat_id"].ToString(),
                            Discount = discountValue,
                            Is_cancelled = reader.GetBoolean("is_cancelled")
                        };

                        ticketDetails.flight = new Flight
                        {
                            fid = reader["fid"].ToString(),
                            depart_time = reader.GetDateTime("depart_time"),
                            status_ = reader["status_"].ToString(),
                            arrival_time = reader.GetDateTime("arrival_time"),
                            duration = flightDuration // Correctly set the duration
                        };

                        ticketDetails.route = new Route
                        {
                            ro_id = reader["ro_id"].ToString(),
                            start_airport = reader["start_airport"].ToString(),
                            end_airport = reader["end_airport"].ToString(),
                            distance = reader.GetDouble("distance"),
                            duration_in_hours = reader.GetDouble("duration_in_hours"),
                            base_price = reader.GetDecimal("base_price")
                        };
                    }
                }
            }
        }

        return View(ticketDetails);
    }


    public IActionResult RefundRequest(string id)
    {
        var refundRequest = new RefundRequest
        {
            Ticket_ID = id,
            date_ = DateTime.Now
        };

        return View(refundRequest);
    }


    public IActionResult SubmitRefund(RefundRequest request)
    {
        // Setting a success message to TempData
        TempData["SuccessMessage"] = "Your refund request has been recorded. We will inform you of any updates.";

        // Define the query to insert the refund request into the refund table
        string query = @"
        INSERT INTO refund (Ticket_ID, Amount, date_, Status_, description_)
        VALUES (@Ticket_ID, NULL, @RequestDate, 'Pending', @Description)";

        using (var conn = new MySqlConnection(connStr))
        {
            try
            {
                conn.Open();

             
                using (var cmd = new MySqlCommand(query, conn))
                {
                   
                    cmd.Parameters.AddWithValue("@Ticket_ID", request.Ticket_ID);
                    cmd.Parameters.AddWithValue("@RequestDate", DateTime.Now); 
                    cmd.Parameters.AddWithValue("@Description",
                        request.description_); 

                 
                    cmd.ExecuteNonQuery();
                }
            }
            catch (Exception ex)
            {
               
                TempData["ErrorMessage"] = "You Already Have A Pending Request ";
            }
        }

Views/Passenger/BaggageRecord.cshtml
@model IEnumerable<Baggage>

<div class="container py-5">
    <div class="row">
        <div class="col-12">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h2>Your Baggage Records</h2>
                <a href="@Url.Action("profile", "Passenger", new { id = SessionID.Instance.passengerID })" class="btn btn-outline-primary">
                    <i class="bi bi-arrow-left"></i> Back to Profile
                </a>
            </div>
            
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead class="table-light">
                        <tr>
                            <th>Baggage Tag</th>
                            <th>Cargo ID</th>
                            <th>Weight (kg)</th>
                            <th>Type</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var baggage in Model)
                        {
                            <tr>
                                <td>@baggage.TAG</td>
                                <td>@baggage.Cargo_ID</td>
                                <td>@baggage.Weight_</td>
                                <td>@baggage.Type_</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Views/Passenger/PassengerProfile.cshtml
@model Passenger

<div class="container py-5">
    <div class="row">
        <div class="col-lg-4">
            <div class="card mb-4">
                <div class="card-body text-center">
                    <!--<img src="~/images/default-profile.jpg" alt="Profile Picture" class="rounded-circle img-fluid" style="width: 150px;">-->
                    <h5 class="my-3">Hello, @Model.Name_!</h5>
                    <div class="d-flex justify-content-center mb-2">
                        <span class="badge bg-primary">Passenger</span>
                    </div>
                </div>
            </div>


            <div class="card mb-4">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 text-center">
                            <h6 class="text-primary mb-4">Travel Records</h6>
                            <a href="@Url.Action("TicketRecord", "Passenger", new {Passport_No = @Model.Passport_No})" class="btn btn-primary w-100 mb-3">
                                <i class="bi bi-ticket"></i> View Ticket Record
                            </a>
                            <a href="@Url.Action("BaggageRecord", "Passenger", new {Passport_No = @Model.Passport_No})" class="btn btn-secondary w-100">
                                <i class="bi bi-luggage"></i> View Baggage Record
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="card mb-4">
                <div class="card-body">
                    <div class="row">
                        <a href="@Url.Action("Search", "Flight")" class="btn btn-primary w-100 mb-3">
                            <i class="bi bi-ticket"></i> Search for Flights
                        </a>
                    </div>
                </div>
            </div>

            <div class="card mb-4">
                <div class="card-body">
                    <div class="row">
                        <a href="@Url.Action("ChangePassword", "Account")" class="btn btn-primary w-100 mb-3">
                            <i class="bi bi-ticket"></i> Change Password
                        </a>
                    </div>
                </div>
            </div>
            
        </div>
        
        <div class="col-lg-8">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title mb-4">Personal Information</h5>
                    
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <p class="mb-0">Full Name</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">@Model.Name_</p>
                        </div>
                    </div>
                    
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <p class="mb-0">Email</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">@Model.Email</p>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <p class="mb-0">Gender</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">@Model.Gender</p>
                        </div>
                    </div>
                    
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <p class="mb-0">Phone</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">@Model.Contact_Info</p>
                        </div>
                    </div>
                    
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <p class="mb-0">Date of Birth</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">@Model.Birth_Date.ToString("MMMM dd, yyyy")</p>
                        </div>
                    </div>
                    
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <p class="mb-0">Address</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">@Model.Address</p>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title mb-4">Travel Documents</h5>
                    
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <p class="mb-0">Passport Number</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">@Model.Passport_No</p>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-sm-3">
                            <p class="mb-0">Nationality</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">@Model.Nationality</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @if (TempData["BookingMessage"] != null)
    {
    <div class="alert alert-info">
        @TempData["BookingMessage"]
    </div>
    }
</div>

Views/Passenger/RefundRequest.cshtml
@model RefundRequest

<div class="container py-5">
    <div class="row">
        
        <div class="col-lg-8 mx-auto">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0">Refund Request Form</h4>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("SubmitRefund", "Passenger", FormMethod.Post))
                    {
                        @Html.HiddenFor(m => m.Ticket_ID)
                        
                        <div class="mb-4">
                            <label class="form-label">Please describe your reason for requesting a refund:</label>
                            @Html.TextAreaFor(m => m.description_, new { @class = "form-control", rows = "5", required = "required" })
                        </div>
                        <div class="row">

                            <div class="col-12 mb-4">
                                <a href="@Url.Action("TicketDetails", "Passenger", new { id = Model.Ticket_ID })" class="btn btn-outline-primary">
                                    <i class="bi bi-arrow-left"></i> cancel
                                </a>
                            </div>

                            <div class="col-12 mb-4">

                                <div class="text-end">
                                    <button type="submit" class="btn btn-primary">Submit Refund Request</button>
                                </div>
                                
                            </div>

                            </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Views/Passenger/TicketDetails.cshtml
@model TicketDetails

<div class="container py-5">
    <div class="row">

        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0">Ticket Details</h4>
                </div>
                <div class="card-body">
                    <div class="row mb-4">
                        <div class="col-md-6">
                            <h5>Flight Information</h5>
                            <p><strong>Flight Number:</strong> @Model.flight.fid</p>
                            <p><strong>Aircraft:</strong> @Model.flight.aircraft_id</p>
                            <p><strong>From:</strong> @Model.route.start_airport</p>
                            <p><strong>To:</strong> @Model.route.end_airport</p>
                            <p><strong>Duration:</strong> @Model.flight.duration.ToString(@"hh\:mm")</p>
                        </div>
                        <div class="col-md-6">
                            <h5>Schedule</h5>
                            <p><strong>Departure:</strong> @Model.flight.depart_time.ToString("MMM dd, yyyy HH:mm")</p>
                            <p><strong>Arrival:</strong> @Model.flight.arrival_time.ToString("MMM dd, yyyy HH:mm")</p>
                        </div>
                    </div>

                    <div class="row mb-4">
                        <div class="col-md-6">
                            <h5>Ticket Information</h5>
                            <p><strong>Ticket ID:</strong> @Model.ticket.Ticket_ID</p>
                            <p><strong>Class:</strong> @Model.ticket.Class</p>
                        </div>
                        <div class="col-md-6">
                            <h5>Payment Details</h5>
                            <p><strong>Status:</strong> 
                                <span class="badge bg-@(Model.ticket.Pay_Status == "Paid" ? "success" : "warning")">
                                    @Model.ticket.Pay_Status
                                </span>
                            </p>
                            <p><strong>Price:</strong> $@Model.route.base_price.ToString("N2")</p>
                            <p><strong>Discount:</strong> $@Model.ticket.Discount.ToString("N2")</p>
                            <p><strong>Payment Method:</strong> @Model.ticket.Payment_method</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <h5>Boarding Pass</h5>
                            <div class="card bg-light">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <p><strong>Seat Number:</strong> @Model.ticket.Seat_id</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12 mb-4">
            <a href="@Url.Action("TicketRecord", "Passenger", new {Passport_No = @Model.ticket.Passport_No})" class="btn btn-outline-primary w-100 mb-3">
                <i class="bi bi-arrow-left"></i> Back to Tickets
            </a>
            <a href="@Url.Action("RefundRequest", "Passenger", new { id = Model.ticket.Ticket_ID })" class="btn btn-danger w-100 mb-3">
                <i class="bi bi-exclamation-circle"></i> Request Refund
            </a>
        </div>
    </div>

    @if (TempData["ErrorMessage"] != null)
    {
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
    }
    else
    {
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-info">
                @TempData["SuccessMessage"]
            </div>
        }
    }
    

    
</div>

Views/Passenger/TicketRecord.cshtml
@model TicketRecordViewModel

<div class="container py-5">
    <div class="row">
        <div class="col-12">
            <div class="row">
                <div class="col-9">
                    <h2 class="mb-4">Your Ticket Records</h2>
                </div>
                <div class="col-3">
                    <a href="@Url.Action("profile", "Passenger", new { id = SessionID.Instance.passengerID })" class="btn btn-outline-primary">
                        <i class="bi bi-arrow-left"></i> Back to Profile
                    </a>
                </div>
            </div>

            <div class="table-responsive">
                <table class="table table-hover">
                    <thead class="table-light">
                    <tr>
                        <th>Ticket ID</th>
                        <th>Route</th>
                        <th>Departure Time</th>
                        <th>Class</th>
                        <th>Price</th>
                        <th>Payment Status</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @for (int i = 0; i < Model.Tickets.Count; i++)
                    {
                        <tr>
                            <td>@Model.Tickets[i].Ticket_ID</td>
                            <td>@Model.Routes[i].start_airport - @Model.Routes[i].end_airport</td>
                            <td>@Model.Flights[i].depart_time.ToString("MMM dd, yyyy hh:mm tt")</td>
                            <td>@Model.Tickets[i].Class</td>
                            <td>$@Model.Routes[i].base_price.ToString("N2")</td>
                            <td>
                                <span class="badge bg-@(Model.Tickets[i].Pay_Status == "Paid" ? "success" : "warning")">
                                    @Model.Tickets[i].Pay_Status
                                </span>
                            </td>
                            <td>
                                <a href="@Url.Action("TicketDetails", "Passenger", new { id = Model.Tickets[i].Ticket_ID })"
                                   class="btn btn-primary btn-sm">
                                    View Details
                                </a>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>